Config = {}

Config.SQL = 'oxmysql' --- oxmysql or ghmattisql

Config.Eye = "true" -- If you are using the QB Target then change this to true.

Config.Locations = { 
    ["stations"] = {
        [1] = {label = ('Pawn Shop'), coords = vector4(173.81, -1320.04, 29.35, 250.09)}
	}
}


Config.Items = {
label = "Shop",
    slots = 30,
    items = {
        [1] = {
            name = "phone",
            price = 50,
            amount = 10,
            info = {},
            type = "item",
            slot = 1,
        },
        [2] = {
            name = "radio",
            price = 50,
            amount = 10,
            info = {},
            type = "item",
            slot = 2,
        },
        [3] = {
            name = "laptop",
            price = 50,
            amount = 10,
            info = {},
            type = "item",
            slot = 3,
        },
        [4] = {
            name = "smalltv",
            price = 50,
            amount = 10,
            info = {},
            type = "item",
            slot = 4,
        },
        [5] = {
            name = "mediumtv",
            price = 50,
            amount = 10,
            info = {},
            type = "item",
            slot = 5,
        },
        [6] = {
            name = "bigtv",
            price = 50,
            amount = 10,
            info = {},
            type = "item",
            slot = 6,
        },
        [7] = {
            name = "nightvision",
            price = 50,
            amount = 10,
            info = {},
            type = "item",
            slot = 7,
        },
        [8] = {
            name = "burnerphone",
            price = 50,
            amount = 10,
            info = {},
            type = "item",
            slot = 8,
        },
        [9] = {
            name = "noselong",
            price = 50,
            amount = 10,
            info = {},
            type = "item",
            slot = 9,
        },
        [10] = {
            name = "tshirtmask",
            price = 50,
            amount = 10,
            info = {},
            type = "item",
            slot = 10,
        },
        [11] = {
            name = "zak",
            price = 50,
            amount = 10,
            info = {},
            type = "item",
            slot = 11,
        },
        [12] = {
            name = "gorilla",
            price = 50,
            amount = 10,
            info = {},
            type = "item",
            slot = 12,
        },
        [13] = {
            name = "paard",
            price = 50,
            amount = 10,
            info = {},
            type = "item",
            slot = 13,
        },
        [14] = {
            name = "paardu",
            price = 50,
            amount = 10,
            info = {},
            type = "item",
            slot = 14,
        },
        [15] = {
            name = "skullr",
            price = 50,
            amount = 10,
            info = {},
            type = "item",
            slot = 15,
        },[16] = {
            name = "",
            price = 50,
            amount = 10,
            info = {},
            type = "item",
            slot = 16,
        },
        [17] = {
            name = "",
            price = 50,
            amount = 10,
            info = {},
            type = "item",
            slot = 17,
        },
        [18] = {
            name = "",
            price = 50,
            amount = 10,
            info = {},
            type = "item",
            slot = 18,
        },
        [19] = {
            name = "",
            price = 50,
            amount = 10,
            info = {},
            type = "item",
            slot = 19,
        },
        [20] = {
            name = "",
            price = 50,
            amount = 10,
            info = {},
            type = "item",
            slot = 20,
        },[21] = {
            name = "",
            price = 50,
            amount = 10,
            info = {},
            type = "item",
            slot = 21,
        },
        [22] = {
            name = "",
            price = 50,
            amount = 10,
            info = {},
            type = "item",
            slot = 22,
        },
        [23] = {
            name = "",
            price = 50,
            amount = 10,
            info = {},
            type = "item",
            slot = 23,
        },
        [24] = {
            name = "",
            price = 50,
            amount = 10,
            info = {},
            type = "item",
            slot = 24,
        },
        [25] = {
            name = "",
            price = 50,
            amount = 10,
            info = {},
            type = "item",
            slot = 25,
        },
        [26] = {
            name = "",
            price = 50,
            amount = 10,
            info = {},
            type = "item",
            slot = 26,
        },
        [27] = {
            name = "",
            price = 50,
            amount = 10,
            info = {},
            type = "item",
            slot = 27,
        },
        [28] = {
            name = "",
            price = 50,
            amount = 10,
            info = {},
            type = "item",
            slot = 28,
        },
        [29] = {
            name = "",
            price = 50,
            amount = 10,
            info = {},
            type = "item",
            slot = 29,
        },
        [30] = {
            name = "",
            price = 50,
            amount = 10,
            info = {},
            type = "item",
            slot = 30,
        },
	}
	
}